#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         1
bspc config window_gap          12

bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Zathura state=tiled
bspc rule -a Rxvt state=floating rectangle=800x600+0+0

# running polybar
~/.config/polybar/launch.sh &

# battery warning
bat_notify &

# setting kb layout
./kb_layout

# setting wallpaper
feh --bg-scale ~/Bilder/wallpapers/isocube.png &
