#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Zathura state=tiled
bspc rule -a Urxvt state=floating rectangle=800x600+0+0

~/.config/polybar/launch.sh &
bat_notify &
kb_layout

feh --bg-scale ~/Bilder/pluto.jpg &
#bspc config background "#f5f5dc"
